---

  # YUM
  - name: install nfs-utils rpm package
    yum:
      name: nfs-utils
      state: present
    register: nfs_utils_installation_rpm
    until: nfs_utils_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'
    environment: "{{proxy_env}}"

  - name: install kubelet rpm package
    yum:
      name: kubelet-{{ package_versions.kubernetes_rpm }}
      state: present
    register: kubelet_installation_rpm
    until: kubelet_installation_rpm|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'
    environment: "{{proxy_env}}"

  - name: install kubectl rpm package
    yum:
      name: kubectl-{{ package_versions.kubernetes_rpm }}
      state: present
    register: result
    until: result|success
    retries: 3
    delay: 3
    when: "'master' in group_names and ansible_os_family == 'RedHat'"
    environment: "{{proxy_env}}"

  - name: install kubeadm rpm package
    yum:
      name: kubeadm-{{ package_versions.kubernetes_rpm }}
      state: present
    register: result
    until: result|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'RedHat'
    environment: "{{proxy_env}}"

  # DEB
  - name: install nfs-common deb package
    apt:
      name: nfs-common
      state: present
    register: nfs_common_installation_deb
    until: nfs_common_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"

  - name: install kubelet deb package
    apt:
      name: kubelet={{ package_versions.kubernetes_deb }}
      state: present
      default_release: kubernetes-xenial
    register: kubelet_installation_deb
    until: kubelet_installation_deb|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"

  - name: install kubectl deb package
    apt:
      name: kubectl={{ package_versions.kubernetes_deb }}
      state: present
      default_release: kubernetes-xenial
    register: result
    until: result|success
    retries: 3
    delay: 3
    when: "'master' in group_names and ansible_os_family == 'Debian'"
    environment: "{{proxy_env}}"

  - name: install kubeadm deb package
    apt:
      name: kubeadm={{ package_versions.kubernetes_deb }}
      state: present
      default_release: kubernetes-xenial
    register: result
    until: result|success
    retries: 3
    delay: 3
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"
