---
  - hosts: control-plane[0]
    any_errors_fatal: true
    name: "{{ play_name | default('Copy Assets From Remote') }}"
    serial: 1
    become: yes
    vars_files:
      - group_vars/defaults.yaml

    roles:
      - role: artifacts