---
  - hosts: control-plane
    any_errors_fatal: true
    name: "{{ play_name | default('Bootstrap Control Plane') }}"
    serial: 1
    become: yes
    vars_files:
      - group_vars/defaults.yaml

    roles:
      - role: kubeadm-control-plane