---
  - hosts: node
    any_errors_fatal: true
    name: "{{ play_name | default('Bootstrap Nodes') }}"
    serial: 1
    become: yes
    vars_files:
      - group_vars/defaults.yaml

    roles:
      - role: kubeadm-nodes