---

  # DEB
  - name: add Docker deb key
    apt_key:
      url: "{{ docker_deb_gpg_key_url }}"
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"

  - name: add Kubernetes deb key
    apt_key:
      url: "{{ kubernetes_deb_gpg_key_url }}"
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"

  - name: install apt-transport-https package
    apt:
      name: apt-transport-https
      state: latest
      update_cache: yes
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"

  - name: add Docker deb repository
    apt_repository:
      repo: 'deb [arch=amd64] {{ docker_deb_repository_url }} xenial stable'
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"

  - name: add Kubernetes deb repository
    apt_repository:
      repo: 'deb {{ kubernetes_deb_repository_url }} kubernetes-xenial main'
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"

  - name: apt-get update
    apt:
      update_cache: yes
    when: ansible_os_family == 'Debian'
    environment: "{{proxy_env}}"